version: '3'
services:
    base_image:
        image: base_image
        container_name: base_image
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        command: sh -c "yarn install && yarn dev --host"
        ports:
            - 3004:5173
        volumes:
            - .:/app
