version: '3'
services:
    base:
        container_name: base
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        command: sh -c "yarn install && yarn dev --host"
        ports:
            - 3003:5173
        volumes:
            - .:/app
